name: PORTALIS CI/CD
on:
  push:
    branches:
      - development
env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_KEY: ${{ secrets.EC2_KEY }}
  IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t {{ env.IMAGE_TAG }} .
          
      - name: Login TKE Registry
        run: |
          docker login -u ${{ enc.DOCKER_USER }} -p '${{ env.DOCKER_PASSWORD }}'
      
      - name: Publish
        run: |
          docker push {{ env.IMAGE_TAG }}

      - name: 🎉 Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.EC2_KEY }}
          script: deploy.sh
